# Application Name and Server Port
spring.application.name=ProducerService
server.port=8080

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Logging for Debugging
logging.level.org.springframework.kafka=DEBUG

